### PR TITLE
Feature/19 map output

### PR DESCRIPTION
**Pull request by ArnaudDumont**
Working version of the UI. Next phase of work to be prioritized for budget, Rick Frye demo, and release package.

### CODE REVIEW

**Comment by hahnd** [comment]
@ArnaudDumont - I am unable to compile this commit.  The AnalyticSurfaceLegend is not found.  I tried importing it from gov.nasa.worldwindx.examples.analytics, but then I get the error message that the AnalyticSurfaceLegend.fromColorScale method is not found.  Where is this class coming from in your environment?

**Comment by ArnaudDumont** [comment]
Ooops. Sorry, David. I hadn't checked that one in. Funny that it didn't show up as an untracked file. It's there now.

**Comment by hahnd** [comment]
Thanks, that fixed the compiling issue.

**Review by hahnd — APPROVED** [review]
- The Add/Delete row buttons in the "Sensors" section allow me to manipulate the data in the table, but does not affect the sensors on the map.  Does it affect the data going into the model?  If the added/deleted sensors do not have any effect, we should add a pop-up to explain, or just remove the buttons altogether.  

- When adding a new sensor, typing the comma character is not allowed even though commas are automatically added in other cells.  There is not much feedback and the user is stuck until they figure out the problem.

It is unlikely that we have time to address all of these, but just wanted to report them here.

I was able to run all of the cases without any problem.

**Comment by ArnaudDumont** [comment]
Thanks for testing and pointing out the issues:

- The Add/Delete buttons do modify the backing model and can also be saved out, but you're correct that I'm probably not triggering a re-rendering of the map markers. That might be easy to do, and a nice demo feature. I'll look into it.
- The cells limit entry to values that can be parsed for the required types (no commas in doubles), BUT have style renderers that make them easier to read (adding commas to separate long doubles). I should see if I can make it consistent. I'd hate to add a popup, since there's already a red error box around the offending cell, but I agree that it might be a bit cryptic for users.

Thanks!
- -

**Pull request merged**
